

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: pharmacie-backend
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./Fe
      dockerfile: Dockerfile
    container_name: pharmacie-frontend
    ports:
      - "4200:80"   # Acc√®s via http://localhost:4200
    depends_on:
      - backend
